---
name: autolabeler

on:
    pull_request:
        types: [opened, reopened, synchronize]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    autolabeler:
        permissions:
            # write permission is required to create a github release
            contents: write
            # write permission is required for autolabeler
            # otherwise, read permission is required at least
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v6
              with:
                  config-name: release-drafter-config.yml
                  disable-autolabeler: false
                  prerelease: false
                  publish: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
