---
name: Publish Release Beta

on:
    push:
        branches:
            - release-beta
    workflow_dispatch:

permissions:
    contents: read

jobs:
    publish_release_beta:
        permissions:
            # write permission is required to create a github release
            contents: write
            # write permission is required for autolabeler
            # otherwise, read permission is required at least
            pull-requests: read
        runs-on: ubuntu-latest
        steps:
            - name: version
              id: version
              run: |
                  tag=${GITHUB_REF/refs\/tags\//}
                  version=${tag#v}
                  major=${version%%.*}
                  echo "tag=${tag}" >> $GITHUB_OUTPUT
                  echo "version=${version}" >> $GITHUB_OUTPUT
                  echo "major=${major}" >> $GITHUB_OUTPUT

            - name: create release
              id: create_release
              uses: release-drafter/release-drafter@v6
              with:
                  config-name: release-drafter-config.yml
                  disable-autolabeler: true
                  prerelease: true
                  prerelease-identifier: beta   # prerelease x.x.x-beta.x
                  publish: true
                  version: ${{ steps.version.outputs.version }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: test artifact
              id: test_artifact
              if: success()
              run: |
                  echo "tag=${{ steps.create_release.outputs.tag_name }}" >> tag.txt
            - name: upload release assets
              id: upload-release-assets
              if: success()
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  FILES: tag.txt # space separated list of files to upload
              run: |
                  gh release upload --clobber ${{ steps.version.outputs.version }} ${{ env.FILES }}
